//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G10_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int maDiem { get; set; }
        public Nullable<int> maHS { get; set; }
        public Nullable<int> maMon { get; set; }
        public Nullable<double> diemGiuaKy { get; set; }
        public Nullable<double> diemCuoiKy { get; set; }
        public Nullable<System.DateTime> tgNhap { get; set; }
        public Nullable<System.DateTime> tgXoa { get; set; }
        public string danhGia { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
