//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G10_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.Lop = new HashSet<Lop>();
            this.Mon = new HashSet<Mon>();
        }
    
        public int maGV { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string ten { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string diaChi { get; set; }
        public string sdt { get; set; }
        public string bangCap { get; set; }
        public Nullable<System.DateTime> tgBatDau { get; set; }
        public Nullable<System.DateTime> tgKetThuc { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mon> Mon { get; set; }
    }
}
