//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G10_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.Diem = new HashSet<Diem>();
        }
    
        public int maHS { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string ten { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string diaChi { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> tgBatDau { get; set; }
        public Nullable<System.DateTime> tgKetThuc { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<int> maLop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diem { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
