//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G10_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mon()
        {
            this.Diem = new HashSet<Diem>();
        }
    
        public int maMon { get; set; }
        public string tenMon { get; set; }
        public Nullable<int> gvDay { get; set; }
        public Nullable<int> maLop { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<int> maHK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diem { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
