//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G10_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int MaTKB { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> MaMon { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Ca Ca { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual Mon Mon { get; set; }
        public virtual ThoiGianHoc ThoiGianHoc { get; set; }
    }
}
